version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - RAILS_REPO_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/rails_app
      - WEBSERVER_REPO_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/webserver
  build:
    commands:
      - echo Building Rails app image...
      - docker build -f docker/app/Dockerfile -t rails_app:$IMAGE_TAG .
      - docker tag rails_app:$IMAGE_TAG $RAILS_REPO_URI:$IMAGE_TAG
      - docker tag rails_app:$IMAGE_TAG $RAILS_REPO_URI:latest
      - echo Building webserver image...
      - docker build -f docker/nginx/Dockerfile -t webserver:$IMAGE_TAG .
      - docker tag webserver:$IMAGE_TAG $WEBSERVER_REPO_URI:$IMAGE_TAG
      - docker tag webserver:$IMAGE_TAG $WEBSERVER_REPO_URI:latest
  post_build:
    commands:
      - echo Pushing Rails app image...
      - docker push $RAILS_REPO_URI:$IMAGE_TAG
      - docker push $RAILS_REPO_URI:latest
      - echo Pushing webserver image...
      - docker push $WEBSERVER_REPO_URI:$IMAGE_TAG
      - docker push $WEBSERVER_REPO_URI:latest
      - echo Build completed on `date` 